const steps = [
  { id: "IntakeStart" },
  { id: "Shelters" },

  { id: "ContactInfo" },
  { id: "FamilyMembers" },
  { id: "FamilyDemographics" },
  { id: "RaceEthnicityInfo" },
  { id: "BarriersPage" },
  { id: "ChildSchoolInfo" },
  { id: "DomesticViolence" },
  { id: "HomelessHistory" },
  { id: "Insurance" },
  { id: "AdditionalInfo" },
  { id: "Pets" },
  { id: "ClientRelease" },
  { id: "ClientReleaseSignature" },
  { id: "ClientReleaseStaffSig" },
  { id: "ThirdPartyConsent" },
  { id: "ThirdPartySigs" },
  { id: "GuestWaiver" },
  { id: "CaseManagement" },
  { id: "PhotoRelease" },
  { id: "CoreValues" },
  { id: "AntiDiscrimination" },
  { id: "Expectations" },
  { id: "Decorum" },
  { id: "AbideBy" },
  { id: "SuspensionAgreement" },
  { id: "GrievanceAppeal" },
  { id: "Belongings" },
  { id: "Schedule" },
  { id: "Safety" },
  { id: "AnimalNo" },
  { id: "AnimalYes" },
  { id: "Neighborhood" },
  { id: "NeighborhoodExpectations" },
  { id: "IntakeComplete" },
];

export default steps;
