"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const restrictTo_1 = require("../../middleware/restrictTo");
const controllers_1 = require("./shelters/controllers");
const { authRequired } = require('../../middleware/authRequired');
const express = require("express");
const router = express.Router();
const { createOrg, getAllOrgs } = require("./controllers");
router.use(authRequired);
router.route("/").post(createOrg).get(getAllOrgs);
router.route("/:id/shelters").post((0, restrictTo_1.restrictTo)('admin', 'orgAdmin'), controllers_1.createShelter);
exports.default = router;
