FROM ubuntu:16.04

RUN apt-get update && \
  apt-get install -y  curl && \
  curl -fsSL https://deb.nodesource.com/setup_14.x | bash - && \
  apt-get install -y nodejs

WORKDIR /home

COPY package.json ./

RUN npm install && npm install -g expo-cli

COPY . .

CMD [ "npm", "run", "web"]